### ISSUE TITLE
Minimizing Python programs

### ISSUE THREAD

**Issue by rohanpadhye** [renatahodovan/picireny#16] opened 2020-08-07 01:01 UTC
Hi @renatahodovan and @akosthekiss!

First of all, thanks a lot for this great tool! I've been able to use it successfully to minimize inputs using the [XML grammar](https://github.com/antlr/grammars-v4/tree/master/xml) from the ANTLR repository.

I'm now trying to use it with one of the [Python grammars](https://github.com/antlr/grammars-v4/tree/master/python) ([such as this one](https://github.com/antlr/grammars-v4/blob/master/python/python3-py/Python3.g4)), but facing some issues. I'm guessing Python grammars are not self-contained because of the extra logic needed to emit INDENT/DEDENT tokens, but I was wondering if there was a good solution for this. Problem repro below:

---

Let's say I want to find the smallest program that prints "B".

foo.py:
```python
print("A" if False else "B")
```

test.sh
```bash
#!/bin/bash
python foo.py | grep "^B$"
```

I run picireny using the [Python3.g4 grammar](https://raw.githubusercontent.com/antlr/grammars-v4/master/python/python3-py/Python3.g4).
```bash
picireny --input=foo.py --test=test.sh --grammar Python3.g4 --start file_input
```

I get the error: (paths normalized)
```
Building tree with ANTLRv4 for /path/to/foo.py
	antlr: /home/.antlerinator/antlr-4.7.1-complete.jar
	build_hidden_tokens: False
	cleanup: True
	encoding: ascii
	input: /path/to/foo.py
	input_format:
		'':
			files:/path/to/Python3.g4
			islands: {}
			replacements: {}
	lang: python
	out: /path/to/foo.py.20200806_205104
	start: file_input

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/picireny/__main__.py", line 12, in <module>
    execute()
  File "/usr/local/lib/python3.7/site-packages/picireny/cli.py", line 383, in execute
    cleanup=args.cleanup)
  File "/usr/local/lib/python3.7/site-packages/picireny/cli.py", line 206, in build_with_antlr4
    hidden_tokens=build_hidden_tokens, lang=lang)
  File "/usr/local/lib/python3.7/site-packages/picireny/antlr4/hdd_tree_builder.py", line 598, in create_hdd_tree
    prepare_parsing(start_grammar)
  File "/usr/local/lib/python3.7/site-packages/picireny/antlr4/hdd_tree_builder.py", line 163, in prepare_parsing
    replacements, action_positions = analyze_grammars(antlr_lexer_class, antlr_parser_class, grammar['files'], grammar['replacements'])
  File "/usr/local/lib/python3.7/site-packages/picireny/antlr4/grammar_analyzer.py", line 267, in analyze_grammars
    elements[i].children = [elements[rules[x.ref]]]
KeyError: 'INDENT'
```

---

Am I running the tool incorrectly? Any tips for using grammars with embedded code? Any pointers to other Python3 grammars that you know work well with picreny?

Thanks!

**Comment by renatahodovan** [comment] 2020-08-07 14:25
@rohanpadhye Thanks for the report. It's a valid issue, indeed. @akosthekiss will submit a fix for that soon.

**Comment by rohanpadhye** [comment] 2020-08-07 23:03
Thanks so much for the quick fix! I can confirm that commit b6f9bb9 does in fact resolve the error above. However, with a slightly different starting file for minimization, I get an assertion error within picire. 

foo.py:
```python
if True:
  print("A" if False else "B")
  pass
```

The interestingness test and run command are same as above.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/picireny-19.3+25.gb6f9bb9-py3.7.egg/picireny/__main__.py", line 12, in <module>
    execute()
  File "/usr/local/lib/python3.7/site-packages/picireny-19.3+25.gb6f9bb9-py3.7.egg/picireny/cli.py", line 409, in execute
    cache_class=args.cache, cleanup=args.cleanup)
  File "/usr/local/lib/python3.7/site-packages/picireny-19.3+25.gb6f9bb9-py3.7.egg/picireny/cli.py", line 316, in reduce
    granularity=granularity)
  File "/usr/local/lib/python3.7/site-packages/picireny-19.3+25.gb6f9bb9-py3.7.egg/picireny/hdd.py", line 87, in hddmin
    c = dd.ddmin(level_ids, n=granularity)
  File "/usr/local/lib/python3.7/site-packages/picire/abstract_dd.py", line 46, in ddmin
    assert self._test_config(config, ('assert',)) == self.FAIL
AssertionError
```

Any idea what could be the issue?

**Comment by akosthekiss** [comment] 2020-08-08 10:15
Hi @rohanpadhye,

As it turns out, the Python grammar makes use of the `tokens { ... }` section, which defines tokens without specifying rules for them. This was the original cause of the problem in the grammar analysis phase.

While writing the fix (soon to land in master), I've executed some minimization sessions. I figured it may be interesting to write some notes about them.

**Experiment with the reported example**

I've executed a minimization with the input, test, and grammar files submitted as part of the issue report.

run:
```sh
picireny --input=foo.py --test=test.sh --grammar=Python3.g4 --start=file_input --subset-iterator=skip --complement-iterator=backward
```

foo.py (result):
```py
print(A if False else "B")
```

Notes:
- `--subset-iterator=skip --complement-iterator=backward` may (or may not) result in faster reduction. By experience, it helps when the input is code, but this is only heuristics.
- The output is not that small, it only got rid of the quotes from around "A". However, actually, no more reduction can be expected from HDD (the algorithm under the hood of Picireny). To get `print("B")` as a result, something called *hoisting* would be needed. However that's not implemented in Picireny. Yet.

**Experiment with the second reported example**

I've named the second test file as foo2.py and adapted the tester script as follows:

test.sh:
```sh
#!/bin/bash
python $1 | grep "^B$"
```

This reproduced the reported assertion failure, but then I've amended the command line:

```sh
picireny --input=foo2.py --test=test.sh --grammar=Python3.g4 --start=file_input --subset-iterator=skip --complement-iterator=backward --build-hidden-tokens
```

foo2.py (result):
```py
if True:
  print('' if False else "B")
```

Notes:
- `--build-hidden-tokens` directs Picireny to build tokens from ANTLR's so-called hidden channel in the tree representation that is used during reduction. Usually, this is whitespace. For most of the input formats, this doesn't matter, and not even building them in the tree helps reduction performance. However, this is Python, where whitespace is quite important.
- The test script uses `$1` to refer to the reduced candidate. (The test script in the issue report used a hard-coded file name.)
- During this reduction, `"A"` got replaced by `''` (not by `A` as above). At the moment, I have no idea why the difference...  (If I added `--build-hidden-tokens` to the first example's command line, the result changed there, too.)

**Another experiment**

I've also executed a minimization on the classic example of the program slicing domain, where the sum and product of the first 10 natural numbers are calculated in one go, but we are interested in only one of the results.

sumprod10.py:
```py
#!/usr/bin/env python3

sum = 0
prod = 1
for i in range(1,11):
    sum += i
    prod *= i

print('sum: %d' % sum)
print('prod: %d' % prod)
```

test-prod.sh:
```sh
#! /bin/bash
python3 $1 2>&1 | grep -q "prod: 3628800"
```

run:
```sh
PYTHONOPTIMIZE=1 picireny --input=sumprod10.py --test=test-prod.sh --grammar=Python3.g4 --start=file_input --subset-iterator=skip --complement-iterator=backward --build-hidden-tokens
```

sumprod10.py (result):
```py
prod = 1
for i in range(1,11):
    prod *= i

print('prod: %d' % prod)
```

Notes:
- `PYTHONOPTIMIZE=1` is to disable asserts. That will reduce the number of test executions. I.e., faster reduction in the end. (Disclaimer: Those asserts help catch incorrectly written `test.sh` scripts or flaky tests. Disabling them will remove these safeguards.)

**Yet another experiment with Picire**

Python is quite line-oriented, so one may be tempted to use a line-based reducer instead of a grammar-based one. Therefore, I've executed a minimization on the same example as show above, but using [Picire](https://github.com/renatahodovan/picire).

run:
```sh
PYTHONOPTIMIZE=1 picire --input=sumprod10.py --test=test-prod.sh --subset-iterator=skip --complement-iterator=backward
```

sumprod10.py (result):
```py
prod = 1
for i in range(1,11):
    prod *= i
print('prod: %d' % prod)
```

Notes:
- In this case, line-based reduction works just as well as grammar-based minimization. This definitely cannot be expected in the general case.
- Still, if a grammar is not available, Picire (i.e., DD under the hood) can work as a fallback.

*P.S.*

@rohanpadhye: It would be appreciated if you'd give feedback whether the soon-to-be-landed commit and `--build-hidden-tokens` works for you in more complex scenarios.

**Closed as completed** 2020-08-08 17:06 UTC

**Comment by rohanpadhye** [comment] 2020-08-08 18:27
Thanks @renatahodovan for the follow up and detailed notes. I think I understand how to use picireny better now. I can confirm that the assertion failure disappears for the examples in this issue. I'll try it on more complex cases and let you know if I face any other issues.
